--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin (
    id bigint NOT NULL
);


ALTER TABLE public.admin OWNER TO postgres;

--
-- Name: app_user_favourite_routes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user_favourite_routes (
    favourite_routes_id bigint NOT NULL,
    passenger_id bigint NOT NULL
);


ALTER TABLE public.app_user_favourite_routes OWNER TO postgres;

--
-- Name: chat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat (
    id bigint NOT NULL,
    last_message_date_time timestamp(6) without time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.chat OWNER TO postgres;

--
-- Name: chat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.config (
    id integer NOT NULL,
    luxury_price real,
    standard_price real,
    van_price real
);


ALTER TABLE public.config OWNER TO postgres;

--
-- Name: driver; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.driver (
    car_status smallint,
    is_animal_friendly boolean,
    is_baby_friendly boolean,
    is_profile_activated boolean,
    model character varying(255),
    number_of_seats integer,
    plate_number character varying(255),
    type smallint,
    id bigint NOT NULL,
    CONSTRAINT driver_car_status_check CHECK (((car_status >= 0) AND (car_status <= 1))),
    CONSTRAINT driver_type_check CHECK (((type >= 0) AND (type <= 2)))
);


ALTER TABLE public.driver OWNER TO postgres;

--
-- Name: driver_account_update_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.driver_account_update_request (
    is_animal_friendly boolean,
    is_baby_friendly boolean,
    number_of_seats integer,
    driver_id bigint NOT NULL,
    address character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    model character varying(255),
    phone_number character varying(255) NOT NULL,
    plate_number character varying(255),
    type character varying(255),
    CONSTRAINT driver_account_update_request_type_check CHECK (((type)::text = ANY ((ARRAY['Standard'::character varying, 'Luxury'::character varying, 'Van'::character varying])::text[])))
);


ALTER TABLE public.driver_account_update_request OWNER TO postgres;

--
-- Name: driver_rating; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.driver_rating (
    rating integer,
    driver_id bigint NOT NULL,
    id bigint NOT NULL,
    passenger_id bigint NOT NULL,
    text character varying(255)
);


ALTER TABLE public.driver_rating OWNER TO postgres;

--
-- Name: driver_rating_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.driver_rating ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.driver_rating_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: driver_report; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.driver_report (
    driver_id bigint NOT NULL,
    id bigint NOT NULL,
    passenger_id bigint NOT NULL,
    text character varying(255)
);


ALTER TABLE public.driver_report OWNER TO postgres;

--
-- Name: driver_report_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.driver_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.driver_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message (
    chat_id bigint NOT NULL,
    datetime timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    sender_id bigint NOT NULL,
    text character varying(255) NOT NULL
);


ALTER TABLE public.message OWNER TO postgres;

--
-- Name: message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: passenger; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.passenger (
    id bigint NOT NULL
);


ALTER TABLE public.passenger OWNER TO postgres;

--
-- Name: passenger_favourite_routes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.passenger_favourite_routes (
    passenger_id bigint NOT NULL,
    favourite_routes_id bigint NOT NULL
);


ALTER TABLE public.passenger_favourite_routes OWNER TO postgres;

--
-- Name: registered_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registered_user (
    car_status smallint,
    daily_active_minutes integer,
    is_activated boolean,
    is_animal_friendly boolean,
    is_baby_friendly boolean,
    is_blocked boolean,
    is_profile_activated boolean,
    number_of_seats integer,
    type smallint,
    activation_token_expiry timestamp(6) without time zone,
    id bigint NOT NULL,
    role character varying(31) NOT NULL,
    activation_token character varying(255),
    address character varying(255) NOT NULL,
    block_message character varying(255),
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    mail character varying(255) NOT NULL,
    model character varying(255),
    password character varying(255),
    phone_number character varying(255) NOT NULL,
    picture character varying(255),
    plate_number character varying(255),
    status character varying(255),
    CONSTRAINT registered_user_car_status_check CHECK (((car_status >= 0) AND (car_status <= 1))),
    CONSTRAINT registered_user_role_check CHECK (((role)::text = ANY ((ARRAY['RegisteredUser'::character varying, 'Admin'::character varying, 'Driver'::character varying, 'Passenger'::character varying])::text[]))),
    CONSTRAINT registered_user_status_check CHECK (((status)::text = ANY ((ARRAY['Free'::character varying, 'Busy'::character varying])::text[]))),
    CONSTRAINT registered_user_type_check CHECK (((type >= 0) AND (type <= 2)))
);


ALTER TABLE public.registered_user OWNER TO postgres;

--
-- Name: registered_user_favourite_routes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registered_user_favourite_routes (
    favourite_routes_id bigint NOT NULL,
    passenger_id bigint NOT NULL
);


ALTER TABLE public.registered_user_favourite_routes OWNER TO postgres;

--
-- Name: registered_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.registered_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registered_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ride; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ride (
    has_started boolean,
    is_panic_pressed boolean,
    ride_duration integer,
    ride_price real,
    cancelled_by_id bigint,
    driver_id bigint,
    id bigint NOT NULL,
    passenger_id bigint,
    ride_finish_datetime timestamp(6) without time zone,
    ride_start_datetime timestamp(6) without time zone,
    route_id bigint,
    destination_city character varying(255),
    destination_country character varying(255),
    destination_number character varying(255),
    destination_street character varying(255),
    origin_city character varying(255),
    origin_country character varying(255),
    origin_number character varying(255),
    origin_street character varying(255),
    status character varying(255),
    passengers character varying(255)[],
    CONSTRAINT ride_status_check CHECK (((status)::text = ANY ((ARRAY['Scheduled'::character varying, 'Started'::character varying, 'Finished'::character varying, 'Cancelled'::character varying])::text[])))
);


ALTER TABLE public.ride OWNER TO postgres;

--
-- Name: ride_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ride ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ride_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ride_passengers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ride_passengers (
    passenger_id bigint NOT NULL,
    ride_id bigint NOT NULL
);


ALTER TABLE public.ride_passengers OWNER TO postgres;

--
-- Name: ride_reminder_sent; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ride_reminder_sent (
    id bigint NOT NULL,
    minutes_before integer NOT NULL,
    ride_id bigint NOT NULL,
    sent_at timestamp(6) without time zone NOT NULL,
    minutes integer NOT NULL
);


ALTER TABLE public.ride_reminder_sent OWNER TO postgres;

--
-- Name: ride_reminder_sent_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ride_reminder_sent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ride_reminder_sent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: route; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.route (
    id bigint NOT NULL,
    distance_km double precision
);


ALTER TABLE public.route OWNER TO postgres;

--
-- Name: route_addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.route_addresses (
    route_id bigint NOT NULL,
    city character varying(255),
    country character varying(255),
    number character varying(255),
    street character varying(255)
);


ALTER TABLE public.route_addresses OWNER TO postgres;

--
-- Name: route_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.route ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.route_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_activity_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_activity_session (
    ended_at timestamp(6) without time zone,
    id bigint NOT NULL,
    last_heartbeat_at timestamp(6) without time zone NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_activity_session OWNER TO postgres;

--
-- Name: user_activity_session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_activity_session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_activity_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_favourite_routes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_favourite_routes (
    favourite_routes_id bigint NOT NULL,
    passenger_id bigint NOT NULL
);


ALTER TABLE public.user_favourite_routes OWNER TO postgres;

--
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (id);


--
-- Name: app_user_favourite_routes app_user_favourite_routes_favourite_routes_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user_favourite_routes
    ADD CONSTRAINT app_user_favourite_routes_favourite_routes_id_key UNIQUE (favourite_routes_id);


--
-- Name: chat chat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT chat_pkey PRIMARY KEY (id);


--
-- Name: chat chat_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT chat_user_id_key UNIQUE (user_id);


--
-- Name: config config_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.config
    ADD CONSTRAINT config_pkey PRIMARY KEY (id);


--
-- Name: driver_account_update_request driver_account_update_request_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_account_update_request
    ADD CONSTRAINT driver_account_update_request_pkey PRIMARY KEY (driver_id);


--
-- Name: driver driver_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver
    ADD CONSTRAINT driver_pkey PRIMARY KEY (id);


--
-- Name: driver_rating driver_rating_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_rating
    ADD CONSTRAINT driver_rating_pkey PRIMARY KEY (id);


--
-- Name: driver_report driver_report_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_report
    ADD CONSTRAINT driver_report_pkey PRIMARY KEY (id);


--
-- Name: message message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (id);


--
-- Name: passenger passenger_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.passenger
    ADD CONSTRAINT passenger_pkey PRIMARY KEY (id);


--
-- Name: registered_user registered_user_activation_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registered_user
    ADD CONSTRAINT registered_user_activation_token_key UNIQUE (activation_token);


--
-- Name: registered_user_favourite_routes registered_user_favourite_routes_favourite_routes_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registered_user_favourite_routes
    ADD CONSTRAINT registered_user_favourite_routes_favourite_routes_id_key UNIQUE (favourite_routes_id);


--
-- Name: registered_user registered_user_mail_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registered_user
    ADD CONSTRAINT registered_user_mail_key UNIQUE (mail);


--
-- Name: registered_user registered_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registered_user
    ADD CONSTRAINT registered_user_pkey PRIMARY KEY (id);


--
-- Name: ride ride_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ride
    ADD CONSTRAINT ride_pkey PRIMARY KEY (id);


--
-- Name: ride_reminder_sent ride_reminder_sent_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ride_reminder_sent
    ADD CONSTRAINT ride_reminder_sent_pkey PRIMARY KEY (id);


--
-- Name: route route_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route
    ADD CONSTRAINT route_pkey PRIMARY KEY (id);


--
-- Name: ride_reminder_sent uk2borkr6xpbdunqg8f8jvcnxy6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ride_reminder_sent
    ADD CONSTRAINT uk2borkr6xpbdunqg8f8jvcnxy6 UNIQUE (ride_id, minutes);


--
-- Name: passenger_favourite_routes ukjsvpvgih61giphqhgxedftyde; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.passenger_favourite_routes
    ADD CONSTRAINT ukjsvpvgih61giphqhgxedftyde UNIQUE (favourite_routes_id);


--
-- Name: ride_reminder_sent ukwawynu46pl5ekm9oe2x4j71a; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ride_reminder_sent
    ADD CONSTRAINT ukwawynu46pl5ekm9oe2x4j71a UNIQUE (ride_id, minutes_before);


--
-- Name: user_activity_session user_activity_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_activity_session
    ADD CONSTRAINT user_activity_session_pkey PRIMARY KEY (id);


--
-- Name: user_favourite_routes user_favourite_routes_favourite_routes_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_favourite_routes
    ADD CONSTRAINT user_favourite_routes_favourite_routes_id_key UNIQUE (favourite_routes_id);


--
-- Name: chat fk3ff6yodxdrcqtn6083gyjni1c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fk3ff6yodxdrcqtn6083gyjni1c FOREIGN KEY (user_id) REFERENCES public.registered_user(id);


--
-- Name: route_addresses fk5mcluebngvjk6a3hn5ki9wf5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_addresses
    ADD CONSTRAINT fk5mcluebngvjk6a3hn5ki9wf5 FOREIGN KEY (route_id) REFERENCES public.route(id);


--
-- Name: driver_account_update_request fk6oe26khdvg3r0gh2pxwk7c8so; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_account_update_request
    ADD CONSTRAINT fk6oe26khdvg3r0gh2pxwk7c8so FOREIGN KEY (driver_id) REFERENCES public.registered_user(id);


--
-- Name: message fk8xtmtrv6ynkku9m6upqobu5p2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT fk8xtmtrv6ynkku9m6upqobu5p2 FOREIGN KEY (sender_id) REFERENCES public.registered_user(id);


--
-- Name: registered_user_favourite_routes fk9qassi23uw9nip7qyy1pdwj02; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registered_user_favourite_routes
    ADD CONSTRAINT fk9qassi23uw9nip7qyy1pdwj02 FOREIGN KEY (favourite_routes_id) REFERENCES public.route(id);


--
-- Name: driver_report fkbxonogub9ejf7jy3jab3rk485; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_report
    ADD CONSTRAINT fkbxonogub9ejf7jy3jab3rk485 FOREIGN KEY (driver_id) REFERENCES public.registered_user(id);


--
-- Name: ride fkc3jg12s1rcrb4u1tofu48vpyn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ride
    ADD CONSTRAINT fkc3jg12s1rcrb4u1tofu48vpyn FOREIGN KEY (cancelled_by_id) REFERENCES public.registered_user(id);


--
-- Name: ride_passengers fkcoodie8iq0aosiaoo6vku31o7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ride_passengers
    ADD CONSTRAINT fkcoodie8iq0aosiaoo6vku31o7 FOREIGN KEY (ride_id) REFERENCES public.ride(id);


--
-- Name: registered_user_favourite_routes fkcwdk6wv6rtoae75tcvor1htux; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registered_user_favourite_routes
    ADD CONSTRAINT fkcwdk6wv6rtoae75tcvor1htux FOREIGN KEY (passenger_id) REFERENCES public.registered_user(id);


--
-- Name: user_activity_session fkdotftyt70v3w4chas7dc368kk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_activity_session
    ADD CONSTRAINT fkdotftyt70v3w4chas7dc368kk FOREIGN KEY (user_id) REFERENCES public.registered_user(id);


--
-- Name: driver_report fkdv2jkgtiacklg6rin0icxv04a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_report
    ADD CONSTRAINT fkdv2jkgtiacklg6rin0icxv04a FOREIGN KEY (passenger_id) REFERENCES public.registered_user(id);


--
-- Name: ride_passengers fke55xybovkjwu1af8q688krmfj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ride_passengers
    ADD CONSTRAINT fke55xybovkjwu1af8q688krmfj FOREIGN KEY (passenger_id) REFERENCES public.registered_user(id);


--
-- Name: ride fki1j1o144f1hrph04kxxndcfq5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ride
    ADD CONSTRAINT fki1j1o144f1hrph04kxxndcfq5 FOREIGN KEY (passenger_id) REFERENCES public.registered_user(id);


--
-- Name: message fkmejd0ykokrbuekwwgd5a5xt8a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT fkmejd0ykokrbuekwwgd5a5xt8a FOREIGN KEY (chat_id) REFERENCES public.chat(id);


--
-- Name: passenger_favourite_routes fkmroq35ftf2bj3e4qe0hitdp24; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.passenger_favourite_routes
    ADD CONSTRAINT fkmroq35ftf2bj3e4qe0hitdp24 FOREIGN KEY (passenger_id) REFERENCES public.passenger(id);


--
-- Name: driver_rating fkmy4re3riylvlhi72w5t79ib4w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_rating
    ADD CONSTRAINT fkmy4re3riylvlhi72w5t79ib4w FOREIGN KEY (driver_id) REFERENCES public.registered_user(id);


--
-- Name: ride fkotj3j7nqn7xlsc4t5aaveh5q0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ride
    ADD CONSTRAINT fkotj3j7nqn7xlsc4t5aaveh5q0 FOREIGN KEY (driver_id) REFERENCES public.registered_user(id);


--
-- Name: driver_rating fkp0kmlqnloj4j1po7kqlvx73rq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_rating
    ADD CONSTRAINT fkp0kmlqnloj4j1po7kqlvx73rq FOREIGN KEY (passenger_id) REFERENCES public.registered_user(id);


--
-- Name: ride fks3qboy52sqbflc7595vkd6wlw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ride
    ADD CONSTRAINT fks3qboy52sqbflc7595vkd6wlw FOREIGN KEY (route_id) REFERENCES public.route(id);


--
-- PostgreSQL database dump complete
--

