spring.application.name = project2025

server.port = 8080

#spring.datasource.url = jdbc:postgresql://localhost:5432/Project2025DB
#spring.datasource.url = jdbc:postgresql://192.168.0.28:5432/Project2025DB
spring.datasource.url = jdbc:postgresql://10.1.145.233:5432/Project2025DB
spring.datasource.username = postgres
spring.datasource.password = ftn
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.testWhileIdle = true
spring.datasource.validationQuery = SELECT 1

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true

spring.h2.console.enabled = true
spring.h2.console.path = /h2-console

app.upload.dir=uploads
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
